baseURL = "/RFC8999_Chinese_Translation/"
languageCode = "cn"

title = "RFC8999中文"
defaultContentLanguage  = "cn"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
#externalTitle = "RFC8999 QUIC版本通用属性"
  sidebarColor = "quic"
  themeColour = "DarkSlateGray"
  customCss = ["css/RFC8999.css"]

[[menu.shortcuts]]
  name = "RFC9000 QUIC：一个基于UDP的安全多路复用传输协议"
  weight = 10
  [menu.shortcuts.Params]
    lateralurl = "/RFC9000_Chinese_Translation/"

[markup]
  #defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
